env:
  browser: true
extends:
  - standard
  - eslint:recommended
  - plugin:jest/recommended
  - plugin:react/recommended
  - plugin:jest/recommended
globals:
  fetch: true
rules:
  jest/no-disabled-tests: warn
  jest/no-focused-tests: warn
  jest/no-identical-title: error
  jest/prefer-to-have-length: warn
  react/jsx-uses-react: error
  react/jsx-uses-vars: error
settings:
  react:
    createClass: createReactClass
    pragma: React
    version: '16.0'
  propWrapperFunctions:
  - forbidExtraProps

